name: Create Webdriver Update PR

on:
  schedule:
    - cron:  '0 0 * * WED'
  workflow_dispatch:
    inputs:
      gecko_version:
        description: 'GeckoDriver version?'
        required: true
        default: 'gxx'
      chrome_version:
        description: 'ChromeDriver version?'
        required: true
        default: 'cxx'

jobs:
  create_pr:
    name: Do things
    runs-on: ubuntu-latest
    steps:
    - name: Echo version
      run: |
        if [ "${{ github.event.inputs.gecko_version }}" != "gxx" ]; then
          CHROME_VERS=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        else
          CHROME_VERS=${{ github.event.inputs.gecko_version }}
        fi
        echo $CHROME_VERS
